export default {
    data(){
        return{
            tableColumn:[
                {
                    prop:'codeId',
                    label:'编号',
                    width:200
                },
                {
                    prop:'userName',
                    label:'姓名',
                    width:250
                },
                {
                    prop:'age',
                    label:'年龄',
                    width:250
                },
                {
                    prop:'address',
                    label:'住址',
                    width:250
                },
                {
                    prop:'conPer',
                    label:'联系人',
                    width:250
                },
                {
                    prop:'work',
                    label:'职业',
                    width:300
                },
                {
                    prop:'roleName',
                    label:'角色',
                    width:300
                }
            ]
        }
    }
}